"""add DeathCertificate.childArea

Revision ID: 00ed56ceec88
Revises: d0b82141e59c
Create Date: 2018-10-23 13:39:54.192524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ed56ceec88'
down_revision = 'd0b82141e59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DeathCertificate', sa.Column('childArea', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DeathCertificate', 'childArea')
    # ### end Alembic commands ###
