"""name_birth_idx

Revision ID: 03762844a54d
Revises: 5d4adadb6cdf
Create Date: 2019-03-13 14:35:35.297416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03762844a54d'
down_revision = '5d4adadb6cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('NAME_BIRTH_IDX', 'Client', ['SURNAME', 'NAME1', 'NAME2', 'BIRTHDAY'], unique=False)
    op.drop_index('UNIQUE', table_name='Client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('UNIQUE', 'Client', ['SURNAME', 'NAME1', 'NAME2', 'BIRTHDAY'], unique=True)
    op.drop_index('NAME_BIRTH_IDX', table_name='Client')
    # ### end Alembic commands ###
