"""fix integer columns

Revision ID: 1284c929f0b7
Revises: a9eb80d4acea
Create Date: 2018-11-06 15:34:44.178613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1284c929f0b7'
down_revision = 'a9eb80d4acea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DeathCertificate', 'deathPlace',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('DeathCertificate', 'type',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('PerinatalDeathCertificate', 'type',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PerinatalDeathCertificate', 'type',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('DeathCertificate', 'type',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathPlace',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
