"""add DC.deathComeDTPPeriod_7days

Revision ID: 20d8540d3669
Revises: 6bb80328760e
Create Date: 2018-11-29 16:32:54.515019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20d8540d3669'
down_revision = '6bb80328760e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DeathCertificate', sa.Column('deathComeDTPPeriod_7days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DeathCertificate', 'deathComeDTPPeriod_7days')
    # ### end Alembic commands ###
