"""add right level

Revision ID: 2f2fd4718708
Revises: 1284c929f0b7
Create Date: 2018-11-08 13:25:34.842364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f2fd4718708'
down_revision = '1284c929f0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Right', sa.Column('level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Right', 'level')
    # ### end Alembic commands ###
