"""Extend MKbModelCode.code

Revision ID: 369c5b289efd
Revises: 03762844a54d
Create Date: 2019-06-21 20:06:47.162577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '369c5b289efd'
down_revision = '03762844a54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rbMKBCode', 'name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rbMKBCode', 'name',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
