"""add organisation.code

Revision ID: 501b23affc81
Revises: 568881b83d58
Create Date: 2018-11-02 15:15:55.757673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '501b23affc81'
down_revision = '568881b83d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Organisation', sa.Column('code', sa.String(length=16), nullable=True))
    op.alter_column('Organisation', 'name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Organisation', 'name',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_column('Organisation', 'code')
    # ### end Alembic commands ###
