"""new fields

Revision ID: 568881b83d58
Revises: 8f3f1e9aa1e1
Create Date: 2018-11-02 12:56:00.754256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568881b83d58'
down_revision = '8f3f1e9aa1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BirthCertificate', sa.Column('filledByRelativesMother', sa.Integer(), nullable=True))
    op.add_column('BirthCertificate', sa.Column('updateUserId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'BirthCertificate', 'User', ['updateUserId'], ['id'])
    op.add_column('DeathCertificate', sa.Column('updateUserId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'DeathCertificate', 'User', ['updateUserId'], ['id'])
    op.add_column('Organisation', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('Organisation', sa.Column('okpo', sa.String(length=8), nullable=True))
    op.add_column('PerinatalDeathCertificate', sa.Column('type', sa.String(length=64), nullable=True))
    op.add_column('PerinatalDeathCertificate', sa.Column('updateUserId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'PerinatalDeathCertificate', 'User', ['updateUserId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PerinatalDeathCertificate', type_='foreignkey')
    op.drop_column('PerinatalDeathCertificate', 'updateUserId')
    op.drop_column('PerinatalDeathCertificate', 'type')
    op.drop_column('Organisation', 'okpo')
    op.drop_column('Organisation', 'address')
    op.drop_constraint(None, 'DeathCertificate', type_='foreignkey')
    op.drop_column('DeathCertificate', 'updateUserId')
    op.drop_constraint(None, 'BirthCertificate', type_='foreignkey')
    op.drop_column('BirthCertificate', 'updateUserId')
    op.drop_column('BirthCertificate', 'filledByRelativesMother')
    # ### end Alembic commands ###
