"""Add PDC.childDeathReason

Revision ID: 5d4adadb6cdf
Revises: b99ecb621848
Create Date: 2019-03-11 14:13:25.705175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d4adadb6cdf'
down_revision = 'b99ecb621848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PerinatalDeathCertificate', sa.Column('childDeathReason', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PerinatalDeathCertificate', 'childDeathReason')
    # ### end Alembic commands ###
