"""add doctorWhoCheckedCertificate fields

Revision ID: 634af8cdeaff
Revises: 63cb88afd158
Create Date: 2018-10-23 17:23:36.913077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634af8cdeaff'
down_revision = '63cb88afd158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BirthCertificate', sa.Column('doctorWhoCheckedBirthCertificateFamilyName', sa.String(length=64), nullable=True))
    op.add_column('BirthCertificate', sa.Column('doctorWhoCheckedBirthCertificateFirstName', sa.String(length=64), nullable=True))
    op.add_column('BirthCertificate', sa.Column('doctorWhoCheckedBirthCertificateMiddleName', sa.String(length=64), nullable=True))
    op.add_column('BirthCertificate', sa.Column('doctorWhoCheckedBirthCertificatePost_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'BirthCertificate', 'rbPost', ['doctorWhoCheckedBirthCertificatePost_id'], ['id'])

    op.add_column('DeathCertificate', sa.Column('doctorWhoCheckedDeathCertificateFamilyName', sa.String(length=64), nullable=True))
    op.add_column('DeathCertificate', sa.Column('doctorWhoCheckedDeathCertificateFirstName', sa.String(length=64), nullable=True))
    op.add_column('DeathCertificate', sa.Column('doctorWhoCheckedDeathCertificateMiddleName', sa.String(length=64), nullable=True))
    op.add_column('DeathCertificate', sa.Column('doctorWhoCheckedDeathCertificatePost_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'DeathCertificate', 'rbPost', ['doctorWhoCheckedDeathCertificatePost_id'], ['id'])

    op.add_column('PerinatalDeathCertificate', sa.Column('doctorWhoCheckedPerinatalDeathCertificateFamilyName', sa.String(length=64), nullable=True))
    op.add_column('PerinatalDeathCertificate', sa.Column('doctorWhoCheckedPerinatalDeathCertificateFirstName', sa.String(length=64), nullable=True))
    op.add_column('PerinatalDeathCertificate', sa.Column('doctorWhoCheckedPerinatalDeathCertificateMiddleName', sa.String(length=64), nullable=True))
    op.add_column('PerinatalDeathCertificate', sa.Column('doctorWhoCheckedPerinatalDeathCertificatePost_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'PerinatalDeathCertificate', 'rbPost', ['doctorWhoCheckedPerinatalDeathCertificatePost_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PerinatalDeathCertificate', type_='foreignkey')
    op.drop_column('PerinatalDeathCertificate', 'doctorWhoCheckedPerinatalDeathCertificatePost_id')
    op.drop_column('PerinatalDeathCertificate', 'doctorWhoCheckedPerinatalDeathCertificateMiddleName')
    op.drop_column('PerinatalDeathCertificate', 'doctorWhoCheckedPerinatalDeathCertificateFirstName')
    op.drop_column('PerinatalDeathCertificate', 'doctorWhoCheckedPerinatalDeathCertificateFamilyName')

    op.drop_constraint(None, 'DeathCertificate', type_='foreignkey')
    op.drop_column('DeathCertificate', 'doctorWhoCheckedDeathCertificatePost_id')
    op.drop_column('DeathCertificate', 'doctorWhoCheckedDeathCertificateMiddleName')
    op.drop_column('DeathCertificate', 'doctorWhoCheckedDeathCertificateFirstName')
    op.drop_column('DeathCertificate', 'doctorWhoCheckedDeathCertificateFamilyName')

    op.drop_constraint(None, 'BirthCertificate', type_='foreignkey')
    op.drop_column('BirthCertificate', 'doctorWhoCheckedBirthCertificatePost_id')
    op.drop_column('BirthCertificate', 'doctorWhoCheckedBirthCertificateMiddleName')
    op.drop_column('BirthCertificate', 'doctorWhoCheckedBirthCertificateFirstName')
    op.drop_column('BirthCertificate', 'doctorWhoCheckedBirthCertificateFamilyName')
    # ### end Alembic commands ###
