"""split DeathCertificate.doctorWhoTakeDeathReason

Revision ID: 63cb88afd158
Revises: 00ed56ceec88
Create Date: 2018-10-23 14:57:30.780406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63cb88afd158'
down_revision = '00ed56ceec88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DeathCertificate', sa.Column('doctorWhoTakeDeathReasonFamilyName', sa.String(length=64), nullable=True))
    op.add_column('DeathCertificate', sa.Column('doctorWhoTakeDeathReasonFirstName', sa.String(length=64), nullable=True))
    op.add_column('DeathCertificate', sa.Column('doctorWhoTakeDeathReasonMiddleName', sa.String(length=64), nullable=True))
    op.drop_column('DeathCertificate', 'doctorWhoTakeDeathReason')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DeathCertificate', sa.Column('doctorWhoTakeDeathReason', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('DeathCertificate', 'doctorWhoTakeDeathReasonMiddleName')
    op.drop_column('DeathCertificate', 'doctorWhoTakeDeathReasonFirstName')
    op.drop_column('DeathCertificate', 'doctorWhoTakeDeathReasonFamilyName')
    # ### end Alembic commands ###
