"""add DC.traumaTime

Revision ID: 6bb80328760e
Revises: d3a6610685f8
Create Date: 2018-11-22 19:36:44.884612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bb80328760e'
down_revision = 'd3a6610685f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DeathCertificate', sa.Column('traumaTime', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DeathCertificate', 'traumaTime')
    # ### end Alembic commands ###
