"""add OrganisationAdmin model

Revision ID: 7432f4dc2f9c
Revises: e60cabafb1e4
Create Date: 2018-12-11 19:22:00.810319

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7432f4dc2f9c'
down_revision = 'e60cabafb1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrganisationAdmin',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('organisation_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['organisation_id'], ['Organisation.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_engine='InnoDB')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrganisationAdmin')
    # ### end Alembic commands ###
