"""add index for cert.number

Revision ID: 8f3f1e9aa1e1
Revises: 55f30ad4a233
Create Date: 2018-11-01 17:55:06.959196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3f1e9aa1e1'
down_revision = '55f30ad4a233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_BirthCertificate_number'), 'BirthCertificate', ['number'], unique=False)
    op.create_index(op.f('ix_DeathCertificate_number'), 'DeathCertificate', ['number'], unique=False)
    op.create_index(op.f('ix_PerinatalDeathCertificate_number'), 'PerinatalDeathCertificate', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PerinatalDeathCertificate_number'), table_name='PerinatalDeathCertificate')
    op.drop_index(op.f('ix_DeathCertificate_number'), table_name='DeathCertificate')
    op.drop_index(op.f('ix_BirthCertificate_number'), table_name='BirthCertificate')
    # ### end Alembic commands ###
