"""extra fields filledBy*

Revision ID: 95805ead396a
Revises: 7432f4dc2f9c
Create Date: 2018-12-27 16:07:55.454289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95805ead396a'
down_revision = '7432f4dc2f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DeathCertificate', sa.Column('filledByAccompDocuments', sa.Integer(), nullable=True))
    op.add_column('DeathCertificate', sa.Column('filledByProtocol', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DeathCertificate', 'filledByProtocol')
    op.drop_column('DeathCertificate', 'filledByAccompDocuments')
    # ### end Alembic commands ###
