"""fix DeathCertificate.motherSNILS column: int -> varchar

Revision ID: a8c6ecd960f0
Revises: d86e0d274923
Create Date: 2019-08-26 19:02:26.987703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8c6ecd960f0'
down_revision = 'd86e0d274923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DeathCertificate', 'motherSNILS',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DeathCertificate', 'motherSNILS',
               existing_type=sa.String(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###
