"""added childBirthPlace

Revision ID: a9eb80d4acea
Revises: 3e9c1a8b9b36
Create Date: 2018-11-06 15:07:23.931177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9eb80d4acea'
down_revision = '3e9c1a8b9b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DeathCertificate', sa.Column('childBirthPlace', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DeathCertificate', 'childBirthPlace')
    # ### end Alembic commands ###
