"""add UserPreferences.user_id contraint

Revision ID: b96b236fe7ab
Revises: d98886a1b75e
Create Date: 2018-10-15 14:40:22.577438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96b236fe7ab'
down_revision = 'd98886a1b75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'rbUserPreferences', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rbUserPreferences', type_='foreignkey')
    # ### end Alembic commands ###
