"""new fields

Revision ID: c818531eabec
Revises: 2f2fd4718708
Create Date: 2018-11-08 17:58:19.518734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c818531eabec'
down_revision = '2f2fd4718708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BirthCertificate', sa.Column('recipientDocumentDate_D', mysql.TINYINT(unsigned=True), nullable=True))
    op.add_column('BirthCertificate', sa.Column('recipientDocumentDate_M', mysql.TINYINT(unsigned=True), nullable=True))
    op.add_column('BirthCertificate', sa.Column('recipientDocumentDate_Y', mysql.SMALLINT(unsigned=True), nullable=True))
    op.add_column('BirthCertificate', sa.Column('recipientDocumentOrigin', sa.String(length=128), nullable=True))
    op.add_column('DeathCertificate', sa.Column('recipientDocumentDate_D', mysql.TINYINT(unsigned=True), nullable=True))
    op.add_column('DeathCertificate', sa.Column('recipientDocumentDate_M', mysql.TINYINT(unsigned=True), nullable=True))
    op.add_column('DeathCertificate', sa.Column('recipientDocumentDate_Y', mysql.SMALLINT(unsigned=True), nullable=True))
    op.add_column('DeathCertificate', sa.Column('recipientDocumentOrigin', sa.String(length=128), nullable=True))
    op.add_column('DeathCertificate', sa.Column('traumaDate_D', mysql.TINYINT(unsigned=True), nullable=True))
    op.add_column('DeathCertificate', sa.Column('traumaDate_M', mysql.TINYINT(unsigned=True), nullable=True))
    op.add_column('DeathCertificate', sa.Column('traumaDate_Y', mysql.SMALLINT(unsigned=True), nullable=True))
    op.add_column('PerinatalDeathCertificate', sa.Column('recipientDocumentDate_D', mysql.TINYINT(unsigned=True), nullable=True))
    op.add_column('PerinatalDeathCertificate', sa.Column('recipientDocumentDate_M', mysql.TINYINT(unsigned=True), nullable=True))
    op.add_column('PerinatalDeathCertificate', sa.Column('recipientDocumentDate_Y', mysql.SMALLINT(unsigned=True), nullable=True))
    op.add_column('PerinatalDeathCertificate', sa.Column('recipientDocumentOrigin', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PerinatalDeathCertificate', 'recipientDocumentOrigin')
    op.drop_column('PerinatalDeathCertificate', 'recipientDocumentDate_Y')
    op.drop_column('PerinatalDeathCertificate', 'recipientDocumentDate_M')
    op.drop_column('PerinatalDeathCertificate', 'recipientDocumentDate_D')
    op.drop_column('DeathCertificate', 'traumaDate_Y')
    op.drop_column('DeathCertificate', 'traumaDate_M')
    op.drop_column('DeathCertificate', 'traumaDate_D')
    op.drop_column('DeathCertificate', 'recipientDocumentOrigin')
    op.drop_column('DeathCertificate', 'recipientDocumentDate_Y')
    op.drop_column('DeathCertificate', 'recipientDocumentDate_M')
    op.drop_column('DeathCertificate', 'recipientDocumentDate_D')
    op.drop_column('BirthCertificate', 'recipientDocumentOrigin')
    op.drop_column('BirthCertificate', 'recipientDocumentDate_Y')
    op.drop_column('BirthCertificate', 'recipientDocumentDate_M')
    op.drop_column('BirthCertificate', 'recipientDocumentDate_D')
    # ### end Alembic commands ###
