"""split PerinatalDeathCertificate.motherDOB to YMD

Revision ID: d0b82141e59c
Revises: 940d253b4b0f
Create Date: 2018-10-22 16:17:35.938455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0b82141e59c'
down_revision = '940d253b4b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PerinatalDeathCertificate', sa.Column('motherDOB_D', mysql.TINYINT(unsigned=True), nullable=True))
    op.add_column('PerinatalDeathCertificate', sa.Column('motherDOB_M', mysql.TINYINT(unsigned=True), nullable=True))
    op.add_column('PerinatalDeathCertificate', sa.Column('motherDOB_Y', mysql.SMALLINT(unsigned=True), nullable=True))
    op.drop_column('PerinatalDeathCertificate', 'motherDOB')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PerinatalDeathCertificate', sa.Column('motherDOB', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('PerinatalDeathCertificate', 'motherDOB_Y')
    op.drop_column('PerinatalDeathCertificate', 'motherDOB_M')
    op.drop_column('PerinatalDeathCertificate', 'motherDOB_D')
    # ### end Alembic commands ###
