"""add DeathCertificate.filledByRelatives

Revision ID: d6a09464934f
Revises: b96b236fe7ab
Create Date: 2018-10-16 12:50:20.058015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a09464934f'
down_revision = 'b96b236fe7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DeathCertificate', sa.Column('filledByRelatives', sa.Integer(), nullable=True))
    op.add_column('DeathCertificate', sa.Column('filledByRelativesMother', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DeathCertificate', 'filledByRelativesMother')
    op.drop_column('DeathCertificate', 'filledByRelatives')
    # ### end Alembic commands ###
