"""Extend MKbModelCode.code 2

Revision ID: d86e0d274923
Revises: 369c5b289efd
Create Date: 2019-06-21 20:13:17.741417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd86e0d274923'
down_revision = '369c5b289efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rbMKBCode', 'name',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=320),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rbMKBCode', 'name',
               existing_type=sa.String(length=320),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###
