"""add User.SNILS

Revision ID: d98886a1b75e
Revises: 383eab82896f
Create Date: 2018-10-15 13:05:14.935609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98886a1b75e'
down_revision = '383eab82896f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('SNILS', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'SNILS')
    # ### end Alembic commands ###
