"""change DC reason period types

Revision ID: e4b8375cc8ac
Revises: 95805ead396a
Create Date: 2019-01-09 18:10:24.168129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4b8375cc8ac'
down_revision = '95805ead396a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DeathCertificate', 'deathReasonCausePeriod_Day',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonCausePeriod_Hour',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonCausePeriod_Minutes',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonCausePeriod_Month',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonCausePeriod_Week',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonCausePeriod_Year',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonFirstPeriod_Day',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonFirstPeriod_Hour',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonFirstPeriod_Minutes',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonFirstPeriod_Month',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonFirstPeriod_Week',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonFirstPeriod_Year',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonMainPeriod_Day',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonMainPeriod_Hour',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonMainPeriod_Minutes',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonMainPeriod_Month',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonMainPeriod_Week',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonMainPeriod_Year',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOtherPeriod_Day',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOtherPeriod_Hour',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOtherPeriod_Minutes',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOtherPeriod_Month',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOtherPeriod_Week',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOtherPeriod_Year',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOuterPeriod_Day',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOuterPeriod_Hour',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOuterPeriod_Minutes',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOuterPeriod_Month',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOuterPeriod_Week',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOuterPeriod_Year',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=16),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DeathCertificate', 'deathReasonOuterPeriod_Year',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOuterPeriod_Week',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOuterPeriod_Month',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOuterPeriod_Minutes',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOuterPeriod_Hour',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOuterPeriod_Day',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOtherPeriod_Year',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOtherPeriod_Week',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOtherPeriod_Month',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOtherPeriod_Minutes',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOtherPeriod_Hour',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonOtherPeriod_Day',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonMainPeriod_Year',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonMainPeriod_Week',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonMainPeriod_Month',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonMainPeriod_Minutes',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonMainPeriod_Hour',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonMainPeriod_Day',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonFirstPeriod_Year',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonFirstPeriod_Week',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonFirstPeriod_Month',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonFirstPeriod_Minutes',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonFirstPeriod_Hour',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonFirstPeriod_Day',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonCausePeriod_Year',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonCausePeriod_Week',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonCausePeriod_Month',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonCausePeriod_Minutes',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonCausePeriod_Hour',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('DeathCertificate', 'deathReasonCausePeriod_Day',
                    existing_type=sa.String(length=16),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    # ### end Alembic commands ###
