"""update LoggerModel

Revision ID: e60cabafb1e4
Revises: f0c70c0800a8
Create Date: 2018-12-11 18:50:41.566647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60cabafb1e4'
down_revision = 'f0c70c0800a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Logger', sa.Column('description', sa.Text(length=256), nullable=True))
    op.add_column('Logger', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Logger_datetime'), 'Logger', ['datetime'], unique=False)
    op.create_index(op.f('ix_Logger_method_action'), 'Logger', ['method_action'], unique=False)
    op.create_foreign_key(None, 'Logger', 'Organisation', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Logger', type_='foreignkey')
    op.drop_index(op.f('ix_Logger_method_action'), table_name='Logger')
    op.drop_index(op.f('ix_Logger_datetime'), table_name='Logger')
    op.drop_column('Logger', 'organisation_id')
    op.drop_column('Logger', 'description')
    # ### end Alembic commands ###
