"""fix LoggerrModel.method_action

Revision ID: f0c70c0800a8
Revises: 2171260c3159
Create Date: 2018-12-04 14:13:08.546918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0c70c0800a8'
down_revision = '2171260c3159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Logger', 'method_action',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=24),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Logger', 'method_action',
               existing_type=sa.String(length=24),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
